# Generated by Django 5.1.3 on 2025-02-09 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '社員情報', 'verbose_name_plural': '社員情報一覧'},
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'verbose_name': '社員取得スキル', 'verbose_name_plural': '社員取得スキル一覧'},
        ),
        migrations.AlterModelOptions(
            name='employeetraining',
            options={'verbose_name': '社員取得トレーニング', 'verbose_name_plural': '社員取得トレーニング一覧'},
        ),
        migrations.AlterModelOptions(
            name='skillmaster',
            options={'verbose_name': 'スキルマスタ', 'verbose_name_plural': 'スキルマスタ一覧'},
        ),
        migrations.AlterModelOptions(
            name='trainingmaster',
            options={'verbose_name': 'トレーニングマスタ', 'verbose_name_plural': 'トレーニングマスタ一覧'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=255, verbose_name='社員名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.skillmaster', verbose_name='スキルID'),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.trainingmaster', verbose_name='トレーニングID'),
        ),
        migrations.AlterField(
            model_name='skillmaster',
            name='skill_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='スキルID'),
        ),
        migrations.AlterField(
            model_name='skillmaster',
            name='skill_name',
            field=models.CharField(max_length=255, verbose_name='スキル名'),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='トレーニングID'),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_name',
            field=models.CharField(max_length=255, verbose_name='トレーニング名'),
        ),
    ]
