# Generated by Django 5.1.3 on 2025-02-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employeeskill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=41, verbose_name='社員名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='skillmaster',
            name='skill_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='スキルID'),
        ),
        migrations.AlterField(
            model_name='skillmaster',
            name='skill_name',
            field=models.CharField(max_length=40, verbose_name='スキル名'),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='トレーニングID'),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_name',
            field=models.CharField(max_length=40, verbose_name='トレーニング名'),
        ),
    ]
