# Generated by Django 5.1.3 on 2025-02-11 01:36

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[employee.models.NumValidator()], verbose_name='社員番号'),
        ),
    ]
