# Generated by Django 5.1.3 on 2025-02-11 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='get_date',
            field=models.DateField(default=datetime.date(2025, 2, 11), verbose_name='取得日'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='get_date',
            field=models.DateField(default=datetime.date(2025, 2, 11), verbose_name='取得日'),
        ),
    ]
